INSERT INTO roles (name) VALUES ('ROLE_SUPER_ADMIN') ON DUPLICATE KEY UPDATE name = name;
INSERT INTO roles (name) VALUES ('ROLE_CABINET_CHIEF') ON DUPLICATE KEY UPDATE name = name;
INSERT INTO roles (name) VALUES ('ROLE_DENTIST') ON DUPLICATE KEY UPDATE name = name;
INSERT INTO roles (name) VALUES ('ROLE_PATIENT') ON DUPLICATE KEY UPDATE name = name;